### ISSUE TITLE
classes/Dd.php - PDO Function 

### ISSUE THREAD

**Issue by HowlingWind** [EVE-KILL/zKillboard#299] opened 2015-03-04 15:53 UTC
When running the installation process this error occurs. A lot of this stuff goes well over my head so Im just making you aware of the issue.

PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to connect to database!' in /var/www/zKillboard/classes/Db.php:54
Stack trace:
#0 /var/www/zKillboard/classes/Db.php(101): Db::getPDO()
#1 /var/www/zKillboard/classes/Db.php(177): Db::query('select 1 one fr...', Array, 1, true)
#2 /var/www/zKillboard/install/install.php(144): Db::queryField('select 1 one fr...', 'one', Array, 1)
#3 {main}
  thrown in /var/www/zKillboard/classes/Db.php on line 54

Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to database!' in /var/www/zKillboard/classes/Db.php:54
Stack trace:
#0 /var/www/zKillboard/classes/Db.php(101): Db::getPDO()
#1 /var/www/zKillboard/classes/Db.php(177): Db::query('select 1 one fr...', Array, 1, true)
#2 /var/www/zKillboard/install/install.php(144): Db::queryField('select 1 one fr...', 'one', Array, 1)
#3 {main}
  thrown in /var/www/zKillboard/classes/Db.php on line 54

**Comment by karbowiak** [comment] 2015-03-04 16:13
It's telling you what the issue is, it cannot connect to your database for one reason or another. Be it the username/password that's wrong, or the db simply isn't running on the host/port you defined :)

**Comment by projectgheist** [comment] 2015-03-04 21:39
Related to database issues, I got another error when installing the kb:

```
Adding table zz_crest_killmail ... Error! Removing configuration file.
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'dttm'' in /var/www/clients/client0/web17/web/zKillboard/classes/Db.php:220
Stack trace:
#0 /var/www/clients/client0/web17/web/zKillboard/classes/Db.php(220): PDOStatement->execute(Array)
#1 /var/www/clients/client0/web17/web/zKillboard/install/install.php(250): Db::execute('CREATE TABLE `z...')
#2 /var/www/clients/client0/web17/web/zKillboard/install/install.php(201): loadFile('/var/www/client...')
#3 {main}
  thrown in /var/www/clients/client0/web17/web/zKillboard/classes/Db.php on line 220
```

Then when trying to parse the `zz_crest_killmail.sql` file directly into the db I get the following error:

```
#1067 - Invalid default value for 'dttm' 
```

Changing the type of `dttm` from `datetime` to `timestamp` seems to fix the issue.

**Comment by karbowiak** [comment] 2015-03-09 16:10
Should've been fixed in the latest dump of sql files :)

**Closed by karbowiak** 2015-03-09 16:10 UTC

**Comment by shibdib** [comment] 2015-06-28 00:30
Adding table zz_crest_killmail ... Error! Removing configuration file.
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'dttm'' in /var/www/kb/zKillboard/classes/Db.php:214
Stack trace:
#0 /var/www/kb/zKillboard/classes/Db.php(214): PDOStatement->execute(Array)
#1 /var/www/kb/zKillboard/install/install.php(253): Db::execute('CREATE TABLE `z...')
#2 /var/www/kb/zKillboard/install/install.php(201): loadFile('/var/www/kb/zKi...')
#3 {main}
  thrown in /var/www/kb/zKillboard/classes/Db.php on line 214



still happening
